Monitor.Web/Controllers/ClusterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using Monitor.Services;
using Monitor.Web.Core;

namespace Monitor.Web.Controllers
{
    /// <summary>
    /// 集群控制器
    /// </summary>
    public class ClusterController : BaseController
    {
        private readonly ClusterComputerInfoServices _clusterComputerInfoServices;
        private readonly ClusterHttpWatchService _clusterHttpWatchService;
        private readonly ClusterPerformanceCounterSnapshotService _clusterPerformanceCounterSnapshotService;

        /// <summary>
        /// Initializes a new instance of the
        /// </summary>
        public ClusterController()
        {
            this._clusterComputerInfoServices = new ClusterComputerInfoServices();
            this._clusterHttpWatchService = new ClusterHttpWatchService();
            this._clusterPerformanceCounterSnapshotService = new ClusterPerformanceCounterSnapshotService();
        }

        /// <summary>
        /// WEB集群服务器列表
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult ComputerList()
        {
            return View();
        }

        /// <summary>
        /// 获取WEB集群服务器列表
        /// </summary>
        /// <param name="pageIndex">当前页码</param>
        /// <param name="pageSize">每页大小</param>
        [Route("api/computer/list")]
        public JsonResult GetComputerList(int pageIndex = 1,int pageSize = 10)
        {
            int total = 0;
            var computerInfos = this._clusterComputerInfoServices.GetClusterComputerInfo(pageIndex,pageSize,out total);
            return Success(computerInfos,pageIndex,pageSize,total);
        }

        /// <summary>
        /// 删除WEB站点服务器
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("api/computer/delete")]
        public JsonResult DeleteComputer(string id)
        {
            var objectId = new ObjectId(id);
            this._clusterComputerInfoServices.Delete(objectId);
            return Success();
        }

        
        
    }
}

Monitor.Web/Views/Cluster/Charts.cshtml
@using Monitor.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " 性能监视器统计图";
}

@section scriptSrc{
    <script src="http://cdn.bootcss.com/echarts/3.3.2/echarts.common.js"></script>
}
@section script{
    <script>

        $(function () {

            var cpuChart = echarts.init(document.getElementById('cpuContainer'));
            var iisChart = echarts.init(document.getElementById('iisContainer'));
            var memoryChart = echarts.init(document.getElementById('memoryContainer'));

            var vue = new Vue({
                el: '#app',
                data: {
                    machineIp: '',
                    apiGetChartDataUrl: '@Url.Content("~/")api/GetPerformanceCounterSnapshotCharts',
                    dataList: []
                },
                ready: function () {

                },
                methods: {
                    clickSearchCharts: function (ip) {
                        var vm = this;
                        this.initChartOption();
                        setInterval(function () { vm.getChartData() }, 1000);
                    },
                    
                    initChartOption: function () {

                        // 显示标题，图例和空的坐标轴
                        cpuChart.setOption({
                            title: {
                                left: 'center',
                                text: 'CPU使用率',
                                subtext: 'CPU【max】值统计图,采集单位【秒】'
                            },
                            xAxis: {
                                data: []
                            },
                            yAxis: {
                                min: 0,
                                max: 100
                            },
                            series: [{
                                // 根据名字对应到相应的系列
                                name: 'CPU使用率',
                                smooth: true,
                                symbol: 'none',
                                stack: 'a',
                                areaStyle: {
                                    normal: {}
                                },
                                type: 'line',
                                data: []
                            }]
                        });
                        iisChart.setOption({
                            title: {
                                left: 'center',
                                text: 'IIS请求数',
                                subtext: 'IIS请求数【max】值统计图,采集单位【秒】'
                            },
                            xAxis: {
                                data: []
                            },
                            yAxis: {

                            },
                            series: [{
                                // 根据名字对应到相应的系列
                                name: 'IIS请求数',
                                smooth: true,
                                symbol: 'none',
                                stack: 'a',
                                areaStyle: {
                                    normal: {}
                                },
                                type: 'line',
                                data: []
                            }]
                        });
                        memoryChart.setOption({
                            title: {
                                left: 'center',
                                text: '内存使用',
                                subtext: '内存【max】值统计图,采集单位【秒】'
                            },
                            xAxis: {
                                offset: 10,
                                data: []
                            },
                            yAxis: {

                            },
                            series: [{
                                // 根据名字对应到相应的系列
                                name: '内存使用',
                                smooth: true,
                                symbol: 'none',
                                stack: 'a',
                                areaStyle: {
                                    normal: {}
                                },
                                type: 'line',
                                data: []
                            }]
                        });
                    },
                    getChartData: function () {
                        var vm = this;
                        $.get(vm.apiGetChartDataUrl, { ip: vm.machineIp}, function (response) {
                            var x = [];
                            var cpu = [], iis = [], memory = [];

                            $.each(response, function (index, d) {
                                x.push(d.time);
                                cpu.push(d.cpu);
                                iis.push(d.iis);
                                memory.push(d.memory);
                            })

                            // 填入数据
                            cpuChart.setOption({
                                xAxis: {
                                    data: x
                                },
                                series: [{
                                    data: cpu
                                }]
                            });
                            iisChart.setOption({
                                xAxis: {
                                    data: x
                                },
                                series: [{
                                    data: iis
                                }]
                            });
                            memoryChart.setOption({
                                xAxis: {
                                    data: x
                                },
                                series: [{
                                    data: memory
                                }]
                            });
                        });
                    }
                }
            });
        });
    </script>
}
<div class="container-fluid">
    <div class="info-center">
        <div class="page-header">
            <div class="pull-left">
                <h4>列表信息</h4>
            </div>
        </div>
        <div class="search-box row">
            <div class="col-md-12">
                <div class="form-group">
                    <span class="pull-left form-span">请选择监控日期:</span>
                    <select class="form-control" v-model="machineIp">
                        <option value="">-请选择服务器IP-</option>
                        @{
                            var computerList = ViewBag.ComputerInfoList as List<ClusterComputerInfo>;
                        }
                        @foreach (var item in computerList)
                        {
                            <option value="@item.MachineIp">@item.MachineIp</option>
                        }
                    </select>
                </div>
                <div class="form-group btn-search">
                    <button class="btn btn-primary" v-on:click="clickSearchCharts()"><span class="glyphicon glyphicon-search"></span> 搜索</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-margin">
                
                    <div id="cpuContainer" style="height:400px;"></div>
                    <div id="iisContainer"  style="height:400px;"></div>
                    <div id="memoryContainer" style="height:400px;"></div>
              
            </div>
        </div>
</div>

Monitor.Web/Views/Cluster/ComputerList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " 服务器列表";
}
@section script{
    <script type="text/javascript">
    $(function () {
        var vue = new Vue({
            el: '#app',
            data: {
                total: 0,
                pageSize:10,
                pageOptions: {
                    currentPage: 1,
                    bootstrapMajorVersion: 1,
                    totalPages: 1,
                    alignment: "right",
                    onPageClicked: function (e, originalEvent, type, page) {
                        vue.pageOptions.currentPage = page;
                        vue.getList();
                    }
                },
                apiGetListUrl: '@Url.Action("GetComputerList","Cluster")',
                apiDeleteUrl: '@Url.Action("DeleteComputer","Cluster")',
                dataList: []
            },
            ready: function () {
                this.getList();
            },
            methods: {
                computerDelete: function (id) {
                    var vm = this;
                    app.confirm("确认删除吗", function (result) {
                        if (result) {
                            $.ajax({
                                url: vm.apiDeleteUrl,
                                type: 'get',
                                dataType: 'json',
                                data: { id: id },
                                success: function (response) {
                                    if (response.s === 10006) {
                                        vm.getList();
                                    }
                                }
                            })
                        }
                    });
                },
                getList: function () {
                    var vm = this;
                    $.ajax({
                        url: vm.apiGetListUrl,
                        beforeSend: function () {
                            loading();
                        },
                        type: 'get',
                        dataType: 'json',
                        data: {
                            pageIndex: vm.pageOptions.currentPage,
                            pageSize:vm.pageSize,
                            watchTime: vm.watchTime,
                            url:vm.url,
                            startDate: vm.startDate,
                            endDate: vm.endDate
                        },
                        success: function (response) {
                            if (response.s === 10006) {
                                vm.dataList = response.data;
                                vm.total = response.count;
                                if (vm.total > vm.pageSize) {
                                    vm.pageOptions.totalPages = getTotalPage(response.count, response.pgSize);
                                    $('.pagination').bootstrapPaginator(vm.pageOptions);
                                } else {
                                    $('.pagination').html('');
                                }
                            }

                        },
                        complete: function () {
                            loading(false);
                        }
                    })
                }
            }
        });
    });
    </script>
}
@section scriptSrc{
    <script src="~/Statics/js/bootstrap-paginator.js"></script>
    <script src="~/Statics/js/My97DatePicker/WdatePicker.js"></script>
}
<div class="container-fluid">
    <div class="info-center">
        <div class="page-header">
            <div class="pull-left">
                <h4>列表信息</h4>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-margin table-responsive">
            <table class="table table-bordered table-header table-hover">
                <thead>
                    <tr>
                        <th>
                            服务器名称
                        </th>
                        <th>
                            服务器IP
                        </th>
                        <th>
                            CPU名称
                        </th>
                        <th>
                            CPU个数
                        </th>
                        <th>
                            内存大小
                        </th>
                        <th>
                            系统名称
                        </th>
                        <th>
                            操作
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in dataList">
                        <td>
                            {{item.machineName}}
                        </td>
                        <td>
                            {{item.machineIp}}
                        </td>
                        <td>
                            {{item.cpuName}}
                        </td>
                        <td>
                            {{item.cpuCount}}
                        </td>
                        <td>
                            {{item.totalVisibleMemorySize}}
                        </td>
                        <td>
                            {{item.osName}}
                        </td>
                        <td>
                            <button type="button" v-on:click="computerDelete(item.id)" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span>删除</button>
                        </td>
                    </tr>
                </tbody>
                <tfoot v-show="total>pageSize">
                    <tr>
                        <td colspan="7">
                            <div class="pull-right">
                                <nav>
                                    <div class="pagination pagination-right"></div>
                                </nav>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>

        </div>
</div>
</div>

Monitor.Web/Views/Cluster/HttpWatchList.cshtml
@using Monitor.Models;
@model Webdiyer.WebControls.Mvc.PagedList<ClusterHttpWatch>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " 请求耗时列表";
}
@section script{
    <script>
    $(function () {
        var vue = new Vue({
            el: '#app',
            data: {
                total: 0,
                pageSize: 10,
                pageOptions: {
                    currentPage: 1,
                    bootstrapMajorVersion:1,
                    totalPages: 1,
                    alignment: "right",
                    onPageClicked: function (e, originalEvent, type, page) {
                        vue.pageOptions.currentPage = page;
                        vue.getList();
                    }
                },
                watchTime:'',
                url: '',
                startDate: '',
                endDate:'',
                apiGetListUrl: '@Url.Content("~/")api/GetHttpWatchList',
                dataList: []
            },
            ready: function () {
                this.getList();
            },
            methods: {
                clickSearchHttpWatch: function () {
                    this.pageOptions.currentPage = 1;
                    this.getList();
                },
                getList: function () {
                    var vm = this;
                    $.ajax({
                        url: vm.apiGetListUrl,
                        beforeSend: function () {
                            loading();
                        },
                        type: 'get',
                        dataType: 'json',
                        data: {
                            pageIndex: vm.pageOptions.currentPage,
                            pageSize:vm.pageSize,
                            watchTime: vm.watchTime,
                            url:vm.url,
                            startDate: vm.startDate,
                            endDate: vm.endDate
                        },
                        success: function (response) {
                            if (response.s === 10006) {
                                vm.dataList = response.data;
                                vm.total = response.count;
                                if (vm.total > vm.pageSize) {
                                    vm.pageOptions.totalPages = getTotalPage(response.count, response.pgSize);
                                    $('.pagination').bootstrapPaginator(vm.pageOptions);
                                } else {
                                    $('.pagination').html('');
                                }
                            }

                        },
                        complete: function () {
                            loading(false);
                        }
                    })
                }
            }
        });
    });
    </script>
}
@section scriptSrc{
    <script src="~/Statics/js/bootstrap-paginator.js"></script>
    <script src="~/Statics/js/My97DatePicker/WdatePicker.js"></script>
}
<div class="container-fluid">
    <div class="info-center">
        <div class="page-header">
            <div class="pull-left">
                <h4>列表信息</h4>
            </div>
        </div>
        <div class="search-box row">
            <div class="col-md-12">
                <div class="form-group">
                    <span class="pull-left form-span">请选择监控日期:</span>
                    <input class="form-control input-medium" v-model="startDate" placeholder="开始日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control input-medium" v-model="endDate" placeholder="结束日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control" style="width:250px;" type="text" v-model="url" placeholder="URL或者关键字" />
                </div>
                <div class="form-group">
                     <input class="form-control" type="number" v-model="watchTime"  placeholder="耗时/毫秒" />
                </div>
                <div class="form-group btn-search">
                    <button class="btn btn-primary" v-on:click="clickSearchHttpWatch()"><span class="glyphicon glyphicon-search"></span> 搜索</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-margin">
            <table class="table table-bordered table-header">
                <thead>
                    <tr>
                        <th>
                            请求IP
                        </th>
                        <th>
                            耗时/毫秒
                        </th>
                        <th>
                            请求时间
                        </th>
                        <th>
                            请求地址
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in dataList">
                        <td>
                            {{item.ip}}
                        </td>
                        <td>
                            {{item.timevalue}}
                        </td>
                        <td>
                            {{item.createDate}}
                        </td>
                        <td>
                            {{item.referer}}
                        </td>
                    </tr>
                </tbody>
                <tfoot v-show="total>pageSize">
                    <tr>
                        <td colspan="4">
                            <div class="pull-right">
                                <nav>
                                    <div class="pagination pagination-right"></div>
                                </nav>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
</div>
</div>

Monitor.Web/Views/Cluster/HttpWatchReportList.cshtml
@using Monitor.Models;
@model Webdiyer.WebControls.Mvc.PagedList<ClusterHttpWatch>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " 请求耗时列表";
}
@section script{
    <script>
    $(function () {
        var vue = new Vue({
            el: '#app',
            data: {
                total: 0,
                pageSize:10,
                pageOptions: {
                    currentPage: 1,
                    totalPages: 1,
                    alignment: "right",
                    onPageClicked: function (e, originalEvent, type, page) {
                        vue.pageOptions.currentPage = page;
                        vue.getList();
                    }
                },
                url: '',
                startDate: '',
                endDate:'',
                apiGetListUrl: '@Url.Content("~/")api/GetHttpWatchReportList',
                dataList: []
            },
            ready: function () {
                this.getList();
            },
            methods: {
                clickSearchHttpWatch: function () {
                    this.pageOptions.currentPage = 1;
                    this.getList();
                },
                getList: function () {
                    var vm = this;
                    $.ajax({
                        url: vm.apiGetListUrl,
                        beforeSend: function () {
                            loading();
                        },
                        type: 'get',
                        dataType: 'json',
                        data: {
                            pageIndex: vm.pageOptions.currentPage,
                            pageSize:vm.pageSize,
                            url:vm.url,
                            startDate: vm.startDate,
                            endDate: vm.endDate
                        },
                        success: function (response) {
                            if (response.s === 10006) {
                                vm.dataList = response.data;
                                vm.total = response.count;
                                if (vm.total > vm.pageSize) {
                                    vm.pageOptions.totalPages = getTotalPage(response.count, response.pgSize);
                                    $('.pagination').bootstrapPaginator(vm.pageOptions);
                                } else {
                                    $('.pagination').html('');
                                }
                            }

                        },
                        complete: function () {
                            loading(false);
                        }
                    })
                }
            }
        });
    });
    </script>
}
@section scriptSrc{
    <script src="~/Statics/js/bootstrap-paginator.js"></script>
    <script src="~/Statics/js/My97DatePicker/WdatePicker.js"></script>
}
<div class="container-fluid">
    <div class="info-center">
        <div class="page-header">
            <div class="pull-left">
                <h4>列表信息</h4>
            </div>
        </div>
        <div class="search-box row">
            <div class="col-md-12">
                <div class="form-group">
                    <span class="pull-left form-span">请选择监控日期:</span>
                    <input class="form-control input-medium" v-model="startDate" placeholder="开始日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control input-medium" v-model="endDate" placeholder="结束日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control" style="width:250px;" type="text" v-model="url" placeholder="URL或者关键字" />
                </div>
                <div class="form-group btn-search">
                    <button class="btn btn-primary" v-on:click="clickSearchHttpWatch()"><span class="glyphicon glyphicon-search"></span> 搜索</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-margin">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            URL
                        </th>
                        <th>
                            平均时间/毫秒
                        </th>
                        <th>
                            最大时间/毫秒
                        </th>
                        <th>
                            最小时间/毫秒
                        </th>
                        <th>
                            调用次数
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in dataList">
                        <td>
                            {{item.url}}
                        </td>
                        <td>
                            {{item.avgTime}}
                        </td>
                        <td>
                            {{item.maxTime}}
                        </td>
                        <td>
                            {{item.minTime}}
                        </td>
                        <td>
                            {{item.callCount}}
                        </td>
                    </tr>
                </tbody>
                <tfoot v-show="total>pageSize">
                    <tr>
                        <td colspan="5">
                            <div class="pull-right">
                                <nav>
                                    <div class="pagination pagination-right"></div>
                                </nav>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
    </div>
</div>