Monitor.Web/Controllers/HttpWatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Monitor.Services;

namespace Monitor.Web.Controllers
{
    public class HttpWatchController : BaseController
    {
        private readonly ClusterHttpWatchService _clusterHttpWatchService;

        /// <summary>
        /// Initializes a new instance of the
        /// </summary>
        public HttpWatchController()
        {
            this._clusterHttpWatchService = new ClusterHttpWatchService();
        }
        /// <summary>
        /// WEB Http请求耗时视图
        /// </summary>
        /// <param name="pageIndex">当前页码</param>
        /// <param name="pageSize">每页大小</param>
        /// <returns>ActionResult</returns>
        public ActionResult List(int pageIndex = 1,int pageSize = 10)
        {
            return View();
        }

        /// <summary>
        /// WEB Http请求耗时视图
        /// </summary>
        /// <param name="pageIndex">当前页码</param>
        /// <param name="pageSize">每页大小</param>
        /// <returns>ActionResult</returns>
        public ActionResult ReportList(int pageIndex = 1,int pageSize = 10)
        {
            return View();
        }

        /// <summary>
        /// 获取HTTP耗时列表
        /// </summary>
        /// <param name="watchTime"></param>
        /// <param name="url"></param>
        /// <param name="startDate"></param>
        /// <param name="endDate"></param>
        /// <param name="pageIndex"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        [Route("api/httpwatch/list")]
        public JsonResult GetHttpWatchList(string watchTime,string url,string startDate,string endDate,int pageIndex = 1,int pageSize = 10)
        {
            int total = 0;
            var watchTimeValue = -1;
            if (!string.IsNullOrEmpty(watchTime))
            {
                int.TryParse(watchTime,out watchTimeValue);
            }

            DateTime? start = string.IsNullOrEmpty(startDate) ? null : (DateTime?)DateTime.Parse(startDate);
            DateTime? end = string.IsNullOrEmpty(endDate) ? null : (DateTime?)DateTime.Parse(endDate);

            var computerInfos = _clusterHttpWatchService.GetClusterHttpWatch(watchTimeValue,url,start,end,pageIndex,pageSize,out total);
            return Success(computerInfos,pageIndex,pageSize,total);
        }

        [Route("api/httpwatch/report")]
        public JsonResult GetHttpWatchReportList(string url,string startDate,string endDate,int pageIndex = 1,int pageSize = 10)
        {
            int total = 0;

            DateTime? start = string.IsNullOrEmpty(startDate) ? null : (DateTime?)DateTime.Parse(startDate);
            DateTime? end = string.IsNullOrEmpty(endDate) ? null : (DateTime?)DateTime.Parse(endDate);

            var computerInfos = _clusterHttpWatchService.GetClusterHttpWatchReport(url,start,end,pageIndex,pageSize,out total);
            return Success(computerInfos,pageIndex,pageSize,total);
        }
    }
}

Monitor.Web/Views/HttpWatch/List.cshtml
@using Monitor.Models;
@model Webdiyer.WebControls.Mvc.PagedList<ClusterHttpWatch>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " 请求耗时列表";
}
@section script{
    <script>
    $(function () {
        var vue = new Vue({
            el: '#app',
            data: {
                total: 0,
                pageSize: 10,
                pageOptions: {
                    currentPage: 1,
                    bootstrapMajorVersion:1,
                    totalPages: 1,
                    alignment: "right",
                    onPageClicked: function (e, originalEvent, type, page) {
                        vue.pageOptions.currentPage = page;
                        vue.getList();
                    }
                },
                watchTime:'',
                url: '',
                startDate: '',
                endDate:'',
                apiGetListUrl: '@Url.Action("GetHttpWatchList","HttpWatch")',
                dataList: []
            },
            ready: function () {
                this.getList();
            },
            methods: {
                clickSearchHttpWatch: function () {
                    this.pageOptions.currentPage = 1;
                    this.getList();
                },
                getList: function () {
                    var vm = this;
                    $.ajax({
                        url: vm.apiGetListUrl,
                        beforeSend: function () {
                            loading();
                        },
                        type: 'get',
                        dataType: 'json',
                        data: {
                            pageIndex: vm.pageOptions.currentPage,
                            pageSize:vm.pageSize,
                            watchTime: vm.watchTime,
                            url:vm.url,
                            startDate: vm.startDate,
                            endDate: vm.endDate
                        },
                        success: function (response) {
                            if (response.s === 10006) {
                                vm.dataList = response.data;
                                vm.total = response.count;
                                if (vm.total > vm.pageSize) {
                                    vm.pageOptions.totalPages = getTotalPage(response.count, response.pgSize);
                                    $('.pagination').bootstrapPaginator(vm.pageOptions);
                                } else {
                                    $('.pagination').html('');
                                }
                            }

                        },
                        complete: function () {
                            loading(false);
                        }
                    })
                }
            }
        });
    });
    </script>
}
@section scriptSrc{
    <script src="~/Statics/js/bootstrap-paginator.js"></script>
    <script src="~/Statics/js/My97DatePicker/WdatePicker.js"></script>
}
<div class="container-fluid">
    <div class="info-center">
        <div class="page-header">
            <div class="pull-left">
                <h4>列表信息</h4>
            </div>
        </div>
        <div class="search-box row">
            <div class="col-md-12">
                <div class="form-group">
                    <span class="pull-left form-span">请选择监控日期:</span>
                    <input class="pull-left form-control input-medium" v-model="startDate" placeholder="开始日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control input-medium" v-model="endDate" placeholder="结束日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control" style="width:250px;" type="text" v-model="url" placeholder="URL或者关键字" />
                </div>
                <div class="form-group">
                     <input class="form-control" type="number" v-model="watchTime"  placeholder="耗时/毫秒" />
                </div>
                <div class="form-group btn-search">
                    <button class="btn btn-primary" v-on:click="clickSearchHttpWatch()"><span class="glyphicon glyphicon-search"></span> 搜索</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-margin table-responsive">
            <table class="table table-bordered table-header table-hover">
                <thead>
                    <tr>
                        <th>
                            请求IP
                        </th>
                        <th>
                            耗时/毫秒
                        </th>
                        <th>
                            请求时间
                        </th>
                        <th>
                            请求地址
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in dataList">
                        <td>
                            {{item.ip}}
                        </td>
                        <td>
                            {{item.timevalue}}
                        </td>
                        <td>
                            {{item.createDate}}
                        </td>
                        <td>
                            {{item.referer}}
                        </td>
                    </tr>
                </tbody>
                <tfoot v-show="total>pageSize">
                    <tr>
                        <td colspan="4">
                            <div class="pull-right">
                                <nav>
                                    <div class="pagination pagination-right"></div>
                                </nav>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
</div>
</div>

Monitor.Web/Views/HttpWatch/ReportList.cshtml
@using Monitor.Models;
@model Webdiyer.WebControls.Mvc.PagedList<ClusterHttpWatch>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = " 请求耗时列表";
}
@section script{
    <script>
    $(function () {
        var vue = new Vue({
            el: '#app',
            data: {
                total: 0,
                pageSize:10,
                pageOptions: {
                    currentPage: 1,
                    totalPages: 1,
                    alignment: "right",
                    onPageClicked: function (e, originalEvent, type, page) {
                        vue.pageOptions.currentPage = page;
                        vue.getList();
                    }
                },
                url: '',
                startDate: '',
                endDate:'',
                apiGetListUrl: '@Url.Action("GetHttpWatchReportList","HttpWatch")',
                dataList: []
            },
            ready: function () {
                this.getList();
            },
            methods: {
                clickSearchHttpWatch: function () {
                    this.pageOptions.currentPage = 1;
                    this.getList();
                },
                getList: function () {
                    var vm = this;
                    $.ajax({
                        url: vm.apiGetListUrl,
                        beforeSend: function () {
                            loading();
                        },
                        type: 'get',
                        dataType: 'json',
                        data: {
                            pageIndex: vm.pageOptions.currentPage,
                            pageSize:vm.pageSize,
                            url:vm.url,
                            startDate: vm.startDate,
                            endDate: vm.endDate
                        },
                        success: function (response) {
                            if (response.s === 10006) {
                                vm.dataList = response.data;
                                vm.total = response.count;
                                if (vm.total > vm.pageSize) {
                                    vm.pageOptions.totalPages = getTotalPage(response.count, response.pgSize);
                                    $('.pagination').bootstrapPaginator(vm.pageOptions);
                                } else {
                                    $('.pagination').html('');
                                }
                            }

                        },
                        complete: function () {
                            loading(false);
                        }
                    })
                }
            }
        });
    });
    </script>
}
@section scriptSrc{
    <script src="~/Statics/js/bootstrap-paginator.js"></script>
    <script src="~/Statics/js/My97DatePicker/WdatePicker.js"></script>
}
<div class="container-fluid">
    <div class="info-center">
        <div class="page-header">
            <div class="pull-left">
                <h4>列表信息</h4>
            </div>
        </div>
        <div class="search-box row">
            <div class="col-md-12">
                <div class="form-group">
                    <span class="pull-left form-span">请选择监控日期:</span>
                    <input class="pull-left form-control input-medium" v-model="startDate" placeholder="开始日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control input-medium" v-model="endDate" placeholder="结束日期" type="text" onClick="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm' })" />
                </div>
                <div class="form-group">
                    <input class="form-control" style="width:250px;" type="text" v-model="url" placeholder="URL或者关键字" />
                </div>
                <div class="form-group btn-search">
                    <button class="btn btn-primary" v-on:click="clickSearchHttpWatch()"><span class="glyphicon glyphicon-search"></span> 搜索</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-margin table-responsive">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            URL
                        </th>
                        <th>
                            平均时间/毫秒
                        </th>
                        <th>
                            最大时间/毫秒
                        </th>
                        <th>
                            最小时间/毫秒
                        </th>
                        <th>
                            调用次数
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="item in dataList">
                        <td>
                            {{item.url}}
                        </td>
                        <td>
                            {{item.avgTime}}
                        </td>
                        <td>
                            {{item.maxTime}}
                        </td>
                        <td>
                            {{item.minTime}}
                        </td>
                        <td>
                            {{item.callCount}}
                        </td>
                    </tr>
                </tbody>
                <tfoot v-show="total>pageSize">
                    <tr>
                        <td colspan="5">
                            <div class="pull-right">
                                <nav>
                                    <div class="pagination pagination-right"></div>
                                </nav>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
    </div>
</div>